name: Kodi Addon Build and Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Variables
      id: vars
      run: |
        ADDON_ID=$(basename "$(find ./zips -mindepth 1 -maxdepth 1 -type d)")
        VERSION=$(basename "$(find ./zips/$ADDON_ID -mindepth 1 -maxdepth 1 -type f)" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+)\.zip$/\1/')
        echo "ADDON_ID=${ADDON_ID}" >> $GITHUB_ENV
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Update index.html
      run: |
        ZIP_FILE="${ADDON_ID}-${VERSION}.zip"
        sed -i "s|<a href=.*>|<a href=\"$ZIP_FILE\">$ZIP_FILE</a>|" index.html

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Update index.html with $ZIP_FILE"

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PUSH }}
