name: Kodi Addon Build and Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Scan for ZIP files and update index.html
      run: |
        # Verzeichnis festlegen
        REPO_DIR="repo"

        # Index-Datei erstellen oder leeren
        INDEX_FILE="${REPO_DIR}/index.html"
        echo "<html><body>" > "$INDEX_FILE"

        # Alle ZIP-Dateien scannen
        find "$REPO_DIR" -type f -name "*.zip" | while read ZIP_FILE; do
          # Relativen Pfad zur ZIP-Datei generieren
          RELATIVE_PATH=$(realpath --relative-to="$REPO_DIR" "$ZIP_FILE")

          # Link in index.html hinzufügen
          echo "<a href=\"$RELATIVE_PATH\">$(basename "$RELATIVE_PATH")</a><br>" >> "$INDEX_FILE"
        done

        # HTML-Dokument abschließen
        echo "</body></html>" >> "$INDEX_FILE"

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add repo/index.html
        git commit -m "Update index.html with links to all ZIP files"

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PUSH }}
